routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::middleware(['auth'])->namespace('Backend')->prefix('admin')->group(function() {
    Route::resource('users', 'UsersController');
    Route::resource('plans', 'PlansController');
    Route::resource('coupons', 'CouponsController');
    Route::resource('standard/forms', 'StandardFormsController');
    Route::resource('standard/scopes', 'StandardScopesController');    
    Route::get('standard/moisture', 'StandardMoistureMapController@index')->name('moisture-page');
    Route::get('standard/area', 'StandardAffectedAreasController@areaPage')->name('areas-page');
    Route::get('standard/team', 'StandardTeamsController@teamsPage')->name('teams-page');
    Route::resource('units-of-measure', 'UnitsOfMeasureController');

// ------------------API-----------------//
    Route::resource('standard/areas', 'StandardAffectedAreasController');
    Route::resource('standard/teams', 'StandardTeamsController');
    Route::resource('standard/structure', 'StardardMoistureMapStructureController');
    Route::resource('standard/material', 'StardardMoistureMapMaterialController');
    Route::get('uoms/jsonResult', 'UnitsOfMeasureController@jsonResult');
    Route::get('standard-scopes/form', 'StandardScopesController@form');
    Route::post('standard-scopes/form-update', 'StandardScopesController@formUpdate');
    Route::get('standard-moisture/form', 'StandardMoistureMapController@form');
    Route::post('standard-moisture/form-update', 'StandardMoistureMapController@formUpdate');
    Route::get('standard-areas/form', 'StandardAffectedAreasController@form');
    Route::post('standard-areas/form-update', 'StandardAffectedAreasController@formUpdate');
});

Route::middleware([])->namespace('Frontend')->group(function() {
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'main.index']);
});

app/Http/Controllers/Backend/StandardFormsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\DefaultFromData;
use App\Models\DefaultStatement;

use App\Http\Requests\Standards\FormUpdate;
use Prologue\Alerts\Facades\Alert;

class StandardFormsController extends Controller
{
    /**
     * @var DefaultFromData
     */
    private $defaultFormData;

    /**
     * @var DefaultStatement
     */
    private $defaultStatement;
    /**
     * StandardFormsController constructor.
     *
     * @param DefaultFromData $defaultFromData
     * @param DefaultStatement $defaultStatement
     */
    public function __construct(DefaultFromData $defaultFromData, DefaultStatement $defaultStatement)
    {
        $this->defaultFormData = $defaultFromData;
        $this->defaultStatement = $defaultStatement;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $forms = $this->defaultFormData->with(['default_statements', 'form'])->paginate(20);

        return view('dashboard.standard-forms.index', compact('forms'));
    }

    /**
     * @param int $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(int $id)
    {
        $form = $this->defaultFormData->with(['default_statements'])->findOrFail($id);

        return view('dashboard.standard-forms.form', compact('form'));
    }

    /**
     * @param FormUpdate $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(FormUpdate $request)
    {
        $form = $this->defaultFormData->findOrFail($request->get('id'));
        $form->title = $request->get('title');
        $form->name = $request->get('name');
        $form->save();
        if ($request->has('statement_ids')) {
            $statement_ids = $request->get('statement_ids');
            $statement_titles = $request->get('statement_titles');
            $statement_texts = $request->get('statement_texts');
            foreach ($statement_ids as $key => $id) {
                $defaultStatement = $this->defaultStatement->find($id);
                $defaultStatement->update([
                    'title' => $statement_titles[$key],
                    'statement' => $statement_texts[$key]
                ]);
            }
        }
        Alert::success('Form successfully updated')->flash();

        return redirect()->route('forms.index')->with('alerts', Alert::all());
    }
}

resources/views/dashboard/standard-forms/area.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Areas Management
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li><a href="{{ route('forms.index') }}">Forms</a></li>
            <li class="active">Edit Affected Areas</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="{{ route('forms.index') }}"><i class="fa fa-angle-double-left"></i> Back to Forms</a>
            <br>
            <br>
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Edit Affected Areas</div>
                </div>
                <div class="box-body" ng-app="areaApp" ng-controller="areaCtrl">
                    <div ng-if="loading" class="loader">
                    </div>
                    <div ng-if="!loading">
                        <div class="form-group">
                            <label>Menu Name *</label>
                            <input type="text" class="form-control" ng-model="form.name" ng-change="saveForm()">
                        </div>
                        <div class="form-group">
                            <label>Form Title *</label>
                            <input type="text" class="form-control" ng-model="form.title" ng-change="saveForm()">
                        </div>

                        <div class="control-panel">
                            <label> Affected Areas Management </label>
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-striped table-hover areasTable text-center thead-dark" align-v="center">
                                        <tr>
                                            <th> No </th>
                                            <th> Title </th>
                                            <th> Actions </th>
                                        </tr>
                                        <tr ng-repeat='(index, area) in areas'>
                                            <td> <% index+1 %> </td>
                                            <td> <%area.title%> </td>
                                            <td>
                                                <button class="btn" ng-click="deleteArea(area.id)"> 
                                                    <i class="fa fa-trash text-danger"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder="Add Area"  ng-model="newArea">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button" ng-click="addArea()" ng-disabled="newArea===''">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('after_styles')
    <style>
        .box-body {
            min-height: 500px;
        }
        .loader {
            position: absolute;
            left: 50%;
            top: 50%;
            z-index: 1;
            width: 80px;
            height: 80px;
            margin: -40px 0 0 -40px;
            border: 8px solid #f3f3f3;
            border-radius: 50%;
            border-top: 8px solid #3498db;
            -webkit-animation: spin 2s linear infinite;
            animation: spin 2s linear infinite;
        }
        .input-group {
            position: relative;
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            -ms-flex-wrap: wrap;
            flex-wrap: wrap;
            -webkit-box-align: stretch;
            -ms-flex-align: stretch;
            align-items: stretch;
            width: 100%;
        }
        .input-group>.form-control {
            position: relative;
            -webkit-box-flex: 1;
            -ms-flex: 1 1 auto;
            flex: 1 1 auto;
            width: 1%;
            margin-bottom: 0;
        }
        .input-group-append, .input-group-prepend {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
        }
    </style>
@endsection
@section('after_vendor_scripts')
    <script src="{{ asset('js/areas/app.js') }}"></script>
@endsection

resources/views/dashboard/standard-forms/form.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Forms
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li><a href="{{ route('forms.index') }}">Forms</a></li>
            <li class="active">Edit {{ $form->name }}</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="{{ route('forms.index') }}"><i class="fa fa-angle-double-left"></i> Back to Forms</a>
            <br>
            <br>
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Edit {{ $form->name }}</div>
                </div>

                <div class="box-body">
                    <form method="post" action="{{ route('forms.update', $form->id) }}">
                        <input type="hidden" name="_method" value="patch">
                        <input type="hidden" name="form_id" value="{{ $form->form_id }}">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label>Menu Name *</label>
                            <input type="text" class="form-control" name="name" @isset($form) value="{{ $form->name }}" @endisset>
                            @if($errors->has('name'))
                                <span class="text-danger">{{ $errors->first('name') }}</span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Form Title *</label>
                            <input type="text" class="form-control" name="title" @isset($form) value="{{ $form->title }}" @endisset>
                            @if($errors->has('title'))
                                <span class="text-danger">{{ $errors->first('title') }}</span>
                            @endif
                        </div>
                        <hr>
                        <label>Form Statements</label>
                        @foreach($form->default_statements as $key=>$defaultStatement)                            
                            <div class="form-group">
                                @isset($form)
                                    <input type="hidden" name="statement_ids[]" value="{{$defaultStatement->id}}">
                                @endisset

                                <input type="text" class="form-control" name="statement_titles[]" @isset($form) value="{{$defaultStatement->title}}" @endisset>
                                @if($errors->first("statement_titles.$key"))
                                    <span class="text-danger">
                                        The statement titles field is required.
                                    </span>
                                @endif

                                <textarea class="form-control statements" name="statement_texts[]">
                                @isset($form)
                                    {{ $defaultStatement->statement }}
                                @endisset
                                </textarea>
                            </div>
                        @endforeach

                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-sm btn-primary" id="submitForm">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('after_styles')
    <style>
        .fr-view p{
            font-size: inherit;
        }
    </style>
@endsection
@section('after_scripts')
    <script>
        $(document).ready(function() {
            $('.statements').froalaEditor({
                key: "{{ config('constants.froala_key') }}",
                height: 400,
                fontSizeDefaultSelection: '14',
                fontSizeSelection: true 
            })
        });
    </script>
@endsection

resources/views/dashboard/standard-forms/index.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Forms
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li class="active">Forms</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Forms</div>
                </div>

                <div class="box-body">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Title</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($forms as $form)
                            @if($form->default_statements->count() > 0)
                                <tr>
                                    <td>{{ $form->name }}</td>
                                    <td>{{ $form->title }}</td>
                                    <td>
                                        <a class="btn btn-xs btn-default pull-right" href="{{ route('forms.edit', $form->id) }}">
                                            <i class="fa fa-edit"></i> Edit
                                        </a>
                                    </td>
                                </tr>
                            @elseif($form->form->name==='Project Scope')
                                <?php?>
                                <tr>
                                    <td>{{ $form->name }}</td>
                                    <td>{{ $form->title }}</td>
                                    <td>
                                        <a class="btn btn-xs btn-default pull-right" href="{{ route('scopes.index') }}">
                                            <i class="fa fa-edit"></i> Edit
                                        </a>
                                    </td>
                                </tr>
                            @elseif($form->form->name==='Moisture Map')
                                <?php?>
                                <tr>
                                    <td>{{ $form->name }}</td>
                                    <td>{{ $form->title }}</td>
                                    <td>
                                        <a class="btn btn-xs btn-default pull-right" href="{{ route('moisture-page') }}">
                                            <i class="fa fa-edit"></i> Edit
                                        </a>
                                    </td>
                                </tr>
                            @endif
                        @endforeach
                            <tr>
                                <td> Affected Areas </td>
                                <td> Affected Areas </td>
                                <td>
                                    <a class="btn btn-xs btn-default pull-right" href="{{ route('areas-page') }}">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered table-hover" style="margin-top: 30px">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td> Crews / Teams </td>
                                <td>
                                    <a class="btn btn-xs btn-default pull-right" href="{{ route('teams-page') }}">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                {{ $forms->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/standard-forms/moisture.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Moisture Map Dropdown Management
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li><a href="{{ route('forms.index') }}">Forms</a></li>
            <li class="active">Edit Moisture Map</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="{{ route('forms.index') }}"><i class="fa fa-angle-double-left"></i> Back to Forms</a>
            <br>
            <br>
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Edit Moisture Map</div>
                </div>
                <div class="box-body" ng-app="moistureApp" ng-controller="moistureCtrl">
                    <div ng-if="loading" class="loader">
                    </div>
                    <div ng-if="!loading">
                        <div class="form-group">
                            <label>Menu Name *</label>
                            <input type="text" class="form-control" ng-model="form.name" ng-change="saveForm()">
                        </div>
                        <div class="form-group">
                            <label>Form Title *</label>
                            <input type="text" class="form-control" ng-model="form.title" ng-change="saveForm()">
                        </div>

                        <div class="control-panel">
                            <label> Structure Dropdown Management </label>
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-striped table-hover structuresTable text-center thead-dark" align-v="center">
                                        <tr>
                                            <th> No </th>
                                            <th> Title </th>
                                            <th> Actions </th>
                                        </tr>
                                        <tr ng-repeat='(index, structure) in structures'>
                                            <td> <% index+1 %> </td>
                                            <td> <%structure.title%> </td>
                                            <td>
                                                <button class="btn" ng-click="deleteStructure(structure.id)"> 
                                                    <i class="fa fa-trash text-danger"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder="Add Structure"  ng-model="newStructure">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button" ng-click="addStructure()" ng-disabled="newStructure===''">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="control-panel" style="margin-top:15px">
                            <label> Material Dropdown Management </label>
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-striped table-hover materialsTable text-center thead-dark" align-v="center">
                                        <tr>
                                            <th> No </th>
                                            <th> Title </th>
                                            <th> Actions </th>
                                        </tr>
                                        <tr ng-repeat='(index, material) in materials'>
                                            <td> <% index+1 %> </td>
                                            <td> <%material.title%> </td>
                                            <td>
                                                <button class="btn" ng-click="deleteMaterial(material.id)"> 
                                                    <i class="fa fa-trash text-danger"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder="Add Material"  ng-model="newMaterial">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button" ng-click="addMaterial()" ng-disabled="newMaterial===''">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('after_styles')
    <style>
        .box-body {
            min-height: 500px;
        }
        .loader {
            position: absolute;
            left: 50%;
            top: 50%;
            z-index: 1;
            width: 80px;
            height: 80px;
            margin: -40px 0 0 -40px;
            border: 8px solid #f3f3f3;
            border-radius: 50%;
            border-top: 8px solid #3498db;
            -webkit-animation: spin 2s linear infinite;
            animation: spin 2s linear infinite;
        }
        .input-group {
            position: relative;
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            -ms-flex-wrap: wrap;
            flex-wrap: wrap;
            -webkit-box-align: stretch;
            -ms-flex-align: stretch;
            align-items: stretch;
            width: 100%;
        }
        .input-group>.form-control {
            position: relative;
            -webkit-box-flex: 1;
            -ms-flex: 1 1 auto;
            flex: 1 1 auto;
            width: 1%;
            margin-bottom: 0;
        }
        .input-group-append, .input-group-prepend {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
        }
    </style>
@endsection
@section('after_vendor_scripts')
    <script src="{{ asset('js/moisture/app.js') }}"></script>
@endsection

resources/views/dashboard/standard-forms/teams.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Teams Management
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li><a href="{{ route('forms.index') }}">Forms</a></li>
            <li class="active">Edit Teams</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="{{ route('forms.index') }}"><i class="fa fa-angle-double-left"></i> Back to Forms</a>
            <br>
            <br>
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Edit Teams</div>
                </div>
                <div class="box-body" ng-app="teamsApp" ng-controller="teamsCtrl">
                    <div ng-if="loading" class="loader">
                    </div>
                    <div ng-if="!loading">
                        <div class="control-panel">
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-striped table-hover teamsTable text-center thead-dark" align-v="center">
                                        <tr>
                                            <th> No </th>
                                            <th> Name </th>
                                            <th> Actions </th>
                                        </tr>
                                        <tr ng-repeat='(index, team) in teams'>
                                            <td> <% index+1 %> </td>
                                            <td> <%team.name%> </td>
                                            <td>
                                                <button class="btn" ng-click="deleteTeam(team.id)"> 
                                                    <i class="fa fa-trash text-danger"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="col-md-6">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder="Add Team"  ng-model="newTeam">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button" ng-click="addTeam()" ng-disabled="newTeam===''">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('after_styles')
    <style>
        .box-body {
            min-height: 500px;
        }
        .loader {
            position: absolute;
            left: 50%;
            top: 50%;
            z-index: 1;
            width: 80px;
            height: 80px;
            margin: -40px 0 0 -40px;
            border: 8px solid #f3f3f3;
            border-radius: 50%;
            border-top: 8px solid #3498db;
            -webkit-animation: spin 2s linear infinite;
            animation: spin 2s linear infinite;
        }
        .input-group {
            position: relative;
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
            -ms-flex-wrap: wrap;
            flex-wrap: wrap;
            -webkit-box-align: stretch;
            -ms-flex-align: stretch;
            align-items: stretch;
            width: 100%;
        }
        .input-group>.form-control {
            position: relative;
            -webkit-box-flex: 1;
            -ms-flex: 1 1 auto;
            flex: 1 1 auto;
            width: 1%;
            margin-bottom: 0;
        }
        .input-group-append, .input-group-prepend {
            display: -webkit-box;
            display: -ms-flexbox;
            display: flex;
        }
    </style>
@endsection
@section('after_vendor_scripts')
    <script src="{{ asset('js/teams/app.js') }}"></script>
@endsection