routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::middleware(['auth'])->namespace('Backend')->prefix('admin')->group(function() {
    Route::resource('users', 'UsersController');
    Route::resource('plans', 'PlansController');
    Route::resource('coupons', 'CouponsController');
    Route::resource('standard/forms', 'StandardFormsController');
    Route::resource('standard/scopes', 'StandardScopesController');    
    Route::get('standard/moisture', 'StandardMoistureMapController@index')->name('moisture-page');
    Route::get('standard/area', 'StandardAffectedAreasController@areaPage')->name('areas-page');
    Route::get('standard/team', 'StandardTeamsController@teamsPage')->name('teams-page');
    Route::resource('units-of-measure', 'UnitsOfMeasureController');

// ------------------API-----------------//
    Route::resource('standard/areas', 'StandardAffectedAreasController');
    Route::resource('standard/teams', 'StandardTeamsController');
    Route::resource('standard/structure', 'StardardMoistureMapStructureController');
    Route::resource('standard/material', 'StardardMoistureMapMaterialController');
    Route::get('uoms/jsonResult', 'UnitsOfMeasureController@jsonResult');
    Route::get('standard-scopes/form', 'StandardScopesController@form');
    Route::post('standard-scopes/form-update', 'StandardScopesController@formUpdate');
    Route::get('standard-moisture/form', 'StandardMoistureMapController@form');
    Route::post('standard-moisture/form-update', 'StandardMoistureMapController@formUpdate');
    Route::get('standard-areas/form', 'StandardAffectedAreasController@form');
    Route::post('standard-areas/form-update', 'StandardAffectedAreasController@formUpdate');
});

Route::middleware([])->namespace('Frontend')->group(function() {
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'main.index']);
});

app/Http/Controllers/Api/UomsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\UnitOfMeasure;

use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\JsonResponse;

class UomsController extends ApiController
{
    /**
     * @var UnitOfMeasure
     */
    private $uom;

    /**
     * EquipmentCategoriesController constructor.
     *
     * @param UnitOfMeasure $uom
     */
    public function __construct(UnitOfMeasure $uom)
    {
        $this->uom = $uom;
    }

    /**
     *
     * @return JsonResponse
     */
    public function index(Request $request): JsonResponse
    {
    	$uoms = $this->uom->get();
        return $this->respond(['uoms' => $uoms]);
    }
}

resources/views/dashboard/items/uom/form.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Units Of Measure
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li><a href="{{ route('units-of-measure.index') }}">Units Of Measure</a></li>
            <li class="active">{{ isset($uom) ? 'Edit' : 'Create' }} Unit Of Measure</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="{{ route('units-of-measure.index') }}"><i class="fa fa-angle-double-left"></i> Back to Units of measure</a>
            <br>
            <br>
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">{{ isset($uom) ? 'Edit' : 'Create' }} Unit Of Measure</div>
                </div>

                <div class="box-body">
                    <form method="post"
                          action="@if(isset($uom)) {{ route('units-of-measure.update', $uom->id) }} @else {{ route('units-of-measure.store') }} @endif">
                        @isset($uom)
                            <input type="hidden" name="_method" value="patch">
                        @endisset
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label>Title *</label>
                            <input type="text" class="form-control" name="title" @isset($uom) value="{{ $uom->title }}" @endisset>
                            @if($errors->has('title'))
                                <span class="text-danger">{{ $errors->first('title') }}</span>
                            @endif
                        </div>

                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-sm btn-primary">{{ isset($uom) ? 'Edit' : 'Create' }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/items/uom/index.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Units Of Measure
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li class="active">Units Of Measure</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">

                <div class="box-header with-border">
                    <div class="box-title">Units Of Measure ({{ $uoms->total() }})</div>
                    <a class="btn btn-xs btn-primary pull-right" href="{{ route('units-of-measure.create') }}">
                        <i class="fa fa-plus-circle"></i> Create new
                    </a>
                </div>

                <div class="box-body">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($uoms as $uom)
                            <tr>
                                <td>{{ $uom->title }}</td>
                                <td>
                                    <a class="btn btn-xs btn-danger pull-right remove" data-href="{{ route('units-of-measure.destroy', $uom->id) }}">
                                        <i class="fa fa-trash"></i> Delete
                                    </a>
                                    <a class="btn btn-xs btn-default pull-right" href="{{ route('units-of-measure.edit', $uom->id) }}">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {{ $uoms->links() }}
            </div>
        </div>
    </div>
@endsection