routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::middleware(['auth'])->namespace('Backend')->prefix('admin')->group(function() {
    Route::resource('users', 'UsersController');
    Route::resource('plans', 'PlansController');
    Route::resource('coupons', 'CouponsController');
    Route::resource('standard/forms', 'StandardFormsController');
    Route::resource('standard/scopes', 'StandardScopesController');    
    Route::get('standard/moisture', 'StandardMoistureMapController@index')->name('moisture-page');
    Route::get('standard/area', 'StandardAffectedAreasController@areaPage')->name('areas-page');
    Route::get('standard/team', 'StandardTeamsController@teamsPage')->name('teams-page');
    Route::resource('units-of-measure', 'UnitsOfMeasureController');

// ------------------API-----------------//
    Route::resource('standard/areas', 'StandardAffectedAreasController');
    Route::resource('standard/teams', 'StandardTeamsController');
    Route::resource('standard/structure', 'StardardMoistureMapStructureController');
    Route::resource('standard/material', 'StardardMoistureMapMaterialController');
    Route::get('uoms/jsonResult', 'UnitsOfMeasureController@jsonResult');
    Route::get('standard-scopes/form', 'StandardScopesController@form');
    Route::post('standard-scopes/form-update', 'StandardScopesController@formUpdate');
    Route::get('standard-moisture/form', 'StandardMoistureMapController@form');
    Route::post('standard-moisture/form-update', 'StandardMoistureMapController@formUpdate');
    Route::get('standard-areas/form', 'StandardAffectedAreasController@form');
    Route::post('standard-areas/form-update', 'StandardAffectedAreasController@formUpdate');
});

Route::middleware([])->namespace('Frontend')->group(function() {
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'main.index']);
});

app/Http/Controllers/Backend/PlansController.php
<?php
namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Plans\PlanStore;
use Prologue\Alerts\Facades\Alert;
use Stripe\Plan;
use Stripe\Stripe;

class PlansController extends Controller
{
    /**
     * @var Stripe
     */
    private $stripe;

    /**
     * @var Plan
     */
    private $plan;

    /**
     * PlansController constructor.
     *
     * @param Stripe $stripe
     * @param Plan $plan
     */
    public function __construct(Stripe $stripe, Plan $plan)
    {
        $this->stripe = $stripe;
        $this->plan = $plan;

        $this->stripe->setApiKey(env('STRIPE_SECRET'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $plans = $this->plan->all();

        return view('dashboard.payments.plans.index', compact('plans'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('dashboard.payments.plans.form');
    }

    /**
     * @param PlanStore $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(PlanStore $request)
    {
        $this->plan->create([
            'amount' => $request->get('amount') * 100,
            'interval' => $request->get('interval'),
            'name' => $request->get('name'),
            'trial_period_days' => $request->get('trial_period_days'),
            'currency' => 'usd',
            'id' => kebab_case(strtolower($request->get('name'))),
        ]);

        Alert::success('Plan successfully created')->flash();

        return redirect()->route('plans.index')->with('alerts', Alert::all());
    }

    /**
     * @param $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $plan = $this->plan->retrieve($id);
        $plan->delete();

        Alert::success('Plan successfully deleted')->flash();

        return redirect()->route('plans.index')->with('alerts', Alert::all());
    }
}

resources/views/dashboard/payments/plans/form.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Plans
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li><a href="{{ route('plans.index') }}">Plans</a></li>
            <li class="active">{{ isset($plan) ? 'Edit' : 'Create' }} Plan</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="{{ route('plans.index') }}"><i class="fa fa-angle-double-left"></i> Back to plans</a>
            <br>
            <br>
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">{{ isset($plan) ? 'Edit' : 'Create' }} Plan</div>
                </div>

                <div class="box-body">
                    <form method="post"
                          action="@if(isset($plan)) {{ route('plans.update', $plan->id) }} @else {{ route('plans.store') }} @endif">
                        @isset($plan)
                            <input type="hidden" name="_method" value="patch">
                        @endisset
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" name="name">
                            @if($errors->has('name'))
                                <span class="text-danger">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Price (USD)</label>
                            <input type="number" class="form-control" name="amount">
                            @if($errors->has('amount'))
                                <span class="text-danger">{{ $errors->first('amount') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Trial period (days)</label>
                            <input type="number" class="form-control" name="trial_period_days">
                            @if($errors->has('trial_period_days'))
                                <span class="text-danger">{{ $errors->first('trial_period_days') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Interval</label>
                            <select class="form-control" name="interval">
                                <option value="">-- Please select --</option>
                                <option value="day">Day</option>
                                <option value="week">Week</option>
                                <option value="month">Month</option>
                                <option value="year">Year</option>
                            </select>
                            @if($errors->has('interval'))
                                <span class="text-danger">{{ $errors->first('interval') }}</span>
                            @endif
                        </div>
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-sm btn-primary">{{ isset($plan) ? 'Edit' : 'Create' }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/payments/plans/index.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Plans
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li class="active">Plans</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Plans ({{ count($plans->data) }})</div>
                    <a class="btn btn-xs btn-primary pull-right" href="{{ route('plans.create') }}">
                        <i class="fa fa-plus-circle"></i> Create new
                    </a>
                </div>

                <div class="box-body">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Price</th>
                            <th>Interval</th>
                            <th>Trial period length</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($plans->data as $plan)
                            <tr>
                                <td>{{ $plan->name }}</td>
                                <td>$ {{ $plan->amount / 100 }}</td>
                                <td>{{ $plan->interval }}</td>
                                <td>{{ $plan->trial_period_days }}</td>
                                <td>
                                    <a class="btn btn-xs btn-danger pull-right remove" data-href="{{ route('plans.destroy', $plan->id) }}">
                                        <i class="fa fa-trash"></i> Delete
                                    </a>
                                    <a class="btn btn-xs btn-default pull-right" href="{{ route('plans.edit', $plan->id) }}">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection