routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::middleware(['auth'])->namespace('Backend')->prefix('admin')->group(function() {
    Route::resource('users', 'UsersController');
    Route::resource('plans', 'PlansController');
    Route::resource('coupons', 'CouponsController');
    Route::resource('standard/forms', 'StandardFormsController');
    Route::resource('standard/scopes', 'StandardScopesController');    
    Route::get('standard/moisture', 'StandardMoistureMapController@index')->name('moisture-page');
    Route::get('standard/area', 'StandardAffectedAreasController@areaPage')->name('areas-page');
    Route::get('standard/team', 'StandardTeamsController@teamsPage')->name('teams-page');
    Route::resource('units-of-measure', 'UnitsOfMeasureController');

// ------------------API-----------------//
    Route::resource('standard/areas', 'StandardAffectedAreasController');
    Route::resource('standard/teams', 'StandardTeamsController');
    Route::resource('standard/structure', 'StardardMoistureMapStructureController');
    Route::resource('standard/material', 'StardardMoistureMapMaterialController');
    Route::get('uoms/jsonResult', 'UnitsOfMeasureController@jsonResult');
    Route::get('standard-scopes/form', 'StandardScopesController@form');
    Route::post('standard-scopes/form-update', 'StandardScopesController@formUpdate');
    Route::get('standard-moisture/form', 'StandardMoistureMapController@form');
    Route::post('standard-moisture/form-update', 'StandardMoistureMapController@formUpdate');
    Route::get('standard-areas/form', 'StandardAffectedAreasController@form');
    Route::post('standard-areas/form-update', 'StandardAffectedAreasController@formUpdate');
});

Route::middleware([])->namespace('Frontend')->group(function() {
    Route::get('/', ['uses' => 'HomeController@index', 'as' => 'main.index']);
});

app/Http/Controllers/Backend/CouponsController.php
<?php
namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Coupons\CouponStore;
use Prologue\Alerts\Facades\Alert;
use Stripe\Coupon;
use Stripe\Stripe;

class CouponsController extends Controller
{
    /**
     * @var Stripe
     */
    private $stripe;

    /**
     * @var Coupon
     */
    private $coupon;

    /**
     * CouponsController constructor.
     *
     * @param Stripe $stripe
     * @param Coupon $coupon
     */
    public function __construct(Stripe $stripe, Coupon $coupon)
    {
        $this->stripe = $stripe;
        $this->coupon = $coupon;

        $this->stripe->setApiKey(env('STRIPE_SECRET'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $coupons = $this->coupon->all();

        return view('dashboard.payments.coupons.index', compact('coupons'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('dashboard.payments.coupons.form');
    }

    /**
     * @param CouponStore $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CouponStore $request)
    {
        $this->coupon->create($request->except(['_token']));

        Alert::success('Coupon successfully created')->flash();

        return redirect()->route('coupons.index')->with('alerts', Alert::all());
    }

    /**
     * @param $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $coupon = $this->coupon->retrieve($id);
        $coupon->delete();

        Alert::success('Coupon successfully deleted')->flash();

        return redirect()->route('coupons.index')->with('alerts', Alert::all());
    }
}

resources/views/dashboard/payments/coupons/form.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Coupons
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li><a href="{{ route('coupons.index') }}">Coupons</a></li>
            <li class="active">{{ isset($coupon) ? 'Edit' : 'Create' }} Coupon</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <a href="{{ route('coupons.index') }}"><i class="fa fa-angle-double-left"></i> Back to coupons</a>
            <br>
            <br>
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">{{ isset($coupon) ? 'Edit' : 'Create' }} Plan</div>
                </div>

                <div class="box-body">
                    <form method="post"
                          action="@if(isset($coupon)) {{ route('coupons.update', $coupon->id) }} @else {{ route('coupons.store') }} @endif">
                        @isset($coupon)
                            <input type="hidden" name="_method" value="patch">
                        @endisset
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label>ID *</label>
                            <input type="text" class="form-control" name="id">
                            @if($errors->has('id'))
                                <span class="text-danger">{{ $errors->first('id') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Duration *</label>
                            <select class="form-control" name="duration">
                                <option value="">-- Please select --</option>
                                <option value="forever">Forever</option>
                                <option value="once">Once</option>
                                <option value="repeating">Repeating</option>
                            </select>
                            @if($errors->has('duration'))
                                <span class="text-danger">{{ $errors->first('duration') }}</span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Amount Off (USD)</label>
                            <input type="number" class="form-control" name="amount_off">
                            @if($errors->has('amount_off'))
                                <span class="text-danger">{{ $errors->first('amount_off') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Percent Off (%)</label>
                            <input type="number" class="form-control" name="percent_off" max="100">
                            @if($errors->has('percent_off'))
                                <span class="text-danger">{{ $errors->first('percent_off') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Max redemptions</label>
                            <input type="number" class="form-control" name="max_redemptions" max="100">
                            @if($errors->has('max_redemptions'))
                                <span class="text-danger">{{ $errors->first('max_redemptions') }}</span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Duration in months</label>
                            <input type="number" class="form-control" name="duration_in_months">
                            @if($errors->has('duration_in_months'))
                                <span class="text-danger">{{ $errors->first('duration_in_months') }}</span>
                            @endif
                        </div>

                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-sm btn-primary">{{ isset($coupon) ? 'Edit' : 'Create' }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/payments/coupons/index.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Coupons
        </h1>
        <ol class="breadcrumb">
            <li><a href="{{ url(config('backpack.base.route_prefix', 'admin')) }}">{{ config('backpack.base.project_name') }}</a></li>
            <li class="active">Coupons</li>
        </ol>
    </section>
@endsection


@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-header with-border">
                    <div class="box-title">Coupons ({{ count($coupons->data) }})</div>
                    <a class="btn btn-xs btn-primary pull-right" href="{{ route('coupons.create') }}">
                        <i class="fa fa-plus-circle"></i> Create new
                    </a>
                </div>

                <div class="box-body">
                    <table class="table table-bordered table-hover">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Amount Off</th>
                            <th>Duration</th>
                            <th>Duration in months</th>
                            <th>Times redeemed/Max redemptions</th>
                            <th>Percent Off</th>
                            <th>Valid</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($coupons->data as $coupon)
                            <tr>
                                <td>{{ $coupon->id }}</td>
                                <td>{{ $coupon->amount_off ? '$' . $coupon->amount_off / 100 : 'n/a' }}</td>
                                <td>{{ $coupon->duration }}</td>
                                <td>{{ $coupon->duration_in_months ?? 'n/a' }}</td>
                                <td>{{ $coupon->max_redemptions ? ($coupon->times_redeemed . '/' . $coupon->max_redemptions) : 'n/a' }}</td>
                                <td>{{ $coupon->percent_off ? $coupon->percent_off . '%' : 'n/a' }}</td>
                                <td>{{ $coupon->valid ? 'yes' : 'no' }}</td>
                                <td>
                                    <a class="btn btn-xs btn-danger pull-right remove" data-href="{{ route('coupons.destroy', $coupon->id) }}">
                                        <i class="fa fa-trash"></i> Delete
                                    </a>
                                    <a class="btn btn-xs btn-default pull-right" href="{{ route('coupons.edit', $coupon->id) }}">
                                        <i class="fa fa-edit"></i> Edit
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection